version: 2
jobs:
  build:
    docker:
      - image: themattrix/tox
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -U setuptools pip
            pip install -r requirements.txt
            pip install -r requirements-dev.txt
      - run:
          name: run linter
          command: |
            . venv/bin/activate
            git diff HEAD $(git merge-base HEAD origin/master)  | flake8 --diff --ignore=E501
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            tox
      - run:
          name: check coverage
          command: |
            . venv/bin/activate
            pytest --cov=. --cov-fail-under=95
